language: python
python: 2.7
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
# when travis supports multiple languages this should be test_all
# until this it's fine to rely on a pre-commit hook
  - paver test_all_python
